### ISSUE TITLE
Newest version does not install

### ISSUE THREAD

**Issue by LorduFreeman** [DawidIzydor/advanced-drawing-tools#4]
`Unable to load valid module manifest data from "https://raw.githubusercontent.com/DawidIzydor/advanced-drawing-tools/v.3.1.0/module.json"`

**Comment by laithoron** [comment]
I'm getting the same thing when I try to install too. 13.351

**Comment by laithoron** [comment]
@LorduFreeman 
It looks like I was able to get 3.1.0 to install in FVTT 13.351 by pasting the URL to the module.json from the Releases page into the Manifest URL field at the bottom of Foundry's Install Module screen.

So this worked:
https://github.com/DawidIzydor/advanced-drawing-tools/releases/download/3.1.0/module.json

While the Install button from the search catalogue within FVTT itself did not!

**Comment by Kirsham** [comment]
@laithoron I was able to install using your link, but the module still doesn't work with FVTT 13.351 for me. When active, all drawing objects don't render.

Console error:
`Error: Error thrown in hooked function '' for hook 'getSceneControlButtons'. controls.find is not a function
[Detected 1 package: advanced-drawing-tools(3.1.0)]
    at Hooks.onError (foundry.mjs:23854:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.mjs:23836:36)
    at Hooks.callAll (foundry.mjs:23791:17)
    at #prepareControls (foundry.mjs:116336:13)
    at SceneControls._configureRenderOptions (foundry.mjs:116241:89)
    at #render (foundry.mjs:27219:10)
    at #try (foundry.mjs:7169:23)
    at foundry.mjs:7142:16
    at new Promise (<anonymous>)
    at Semaphore.add (foundry.mjs:7140:12)
    at SceneControls.render (foundry.mjs:27190:28)
    at #initialize (foundry.mjs:94553:23)
    at async #draw (foundry.mjs:94383:5)
    at async Canvas.draw (foundry.mjs:94245:5)
    at async Scene.view (foundry.mjs:46164:7)
    at async Game.initializeCanvas (foundry.mjs:169362:20)
    at async Game.setupGame (foundry.mjs:169129:5)
    at async #initializeGameView (foundry.mjs:170576:5)
    at async Game.initialize (foundry.mjs:169026:5)
    at async window.addEventListener.once (foundry.mjs:181096:3)Caused by: TypeError: controls.find is not a function
[Detected 1 package: advanced-drawing-tools(3.1.0)]
    at Object.fn (controls.js:4:38)
    at #call (foundry.mjs:23832:20)
    at Hooks.callAll (foundry.mjs:23791:17)
    at #prepareControls (foundry.mjs:116336:13)
    at SceneControls._configureRenderOptions (foundry.mjs:116241:89)
    at #render (foundry.mjs:27219:10)
    at #try (foundry.mjs:7169:23)
    at foundry.mjs:7142:16
    at new Promise (<anonymous>)
    at Semaphore.add (foundry.mjs:7140:12)
    at SceneControls.render (foundry.mjs:27190:28)
    at #initialize (foundry.mjs:94553:23)
    at async #draw (foundry.mjs:94383:5)
    at async Canvas.draw (foundry.mjs:94245:5)
    at async Scene.view (foundry.mjs:46164:7)
    at async Game.initializeCanvas (foundry.mjs:169362:20)
    at async Game.setupGame (foundry.mjs:169129:5)
    at async #initializeGameView (foundry.mjs:170576:5)
    at async Game.initialize (foundry.mjs:169026:5)
    at async window.addEventListener.once (foundry.mjs:181096:3)
onError @ foundry.mjs:23855Understand this error
foundry.mjs:23835 Foundry VTT | Error thrown in hooked function 'bound getSceneControlButtons' for hook 'getSceneControlButtons'
#call @ foundry.mjs:23835Understand this warning
foundry.mjs:23855 Error: Error thrown in hooked function 'bound getSceneControlButtons' for hook 'getSceneControlButtons'. e.find is not a function
[Detected 1 package: foundryvtt-simple-calendar(2.4.18)]
    at Hooks.onError (foundry.mjs:23854:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.mjs:23836:36)
    at Hooks.callAll (foundry.mjs:23791:17)
    at #prepareControls (foundry.mjs:116336:13)
    at SceneControls._configureRenderOptions (foundry.mjs:116241:89)
    at #render (foundry.mjs:27219:10)
    at #try (foundry.mjs:7169:23)
    at foundry.mjs:7142:16
    at new Promise (<anonymous>)
    at Semaphore.add (foundry.mjs:7140:12)
    at SceneControls.render (foundry.mjs:27190:28)
    at #initialize (foundry.mjs:94553:23)
    at async #draw (foundry.mjs:94383:5)
    at async Canvas.draw (foundry.mjs:94245:5)
    at async Scene.view (foundry.mjs:46164:7)
    at async Game.initializeCanvas (foundry.mjs:169362:20)
    at async Game.setupGame (foundry.mjs:169129:5)
    at async #initializeGameView (foundry.mjs:170576:5)
    at async Game.initialize (foundry.mjs:169026:5)
    at async window.addEventListener.once (foundry.mjs:181096:3)Caused by: TypeError: e.find is not a function
[Detected 1 package: foundryvtt-simple-calendar(2.4.18)]
    at tt.getSceneControlButtons (index.js:1:172029)
    at #call (foundry.mjs:23832:20)
    at Hooks.callAll (foundry.mjs:23791:17)
    at #prepareControls (foundry.mjs:116336:13)
    at SceneControls._configureRenderOptions (foundry.mjs:116241:89)
    at #render (foundry.mjs:27219:10)
    at #try (foundry.mjs:7169:23)
    at foundry.mjs:7142:16
    at new Promise (<anonymous>)
    at Semaphore.add (foundry.mjs:7140:12)
    at SceneControls.render (foundry.mjs:27190:28)
    at #initialize (foundry.mjs:94553:23)
    at async #draw (foundry.mjs:94383:5)
    at async Canvas.draw (foundry.mjs:94245:5)
    at async Scene.view (foundry.mjs:46164:7)
    at async Game.initializeCanvas (foundry.mjs:169362:20)
    at async Game.setupGame (foundry.mjs:169129:5)
    at async #initializeGameView (foundry.mjs:170576:5)
    at async Game.initialize (foundry.mjs:169026:5)
    at async window.addEventListener.once (foundry.mjs:181096:3)`

**Comment by Wavyisland** [comment]
404 on the 3.1 jason link: https://raw.githubusercontent.com/DawidIzydor/advanced-drawing-tools/v.3.1.0/module.json

**Comment by DawidIzydor** [comment]
I'm fixing this as part of #5
